### ISSUE TITLE
kodi epg

### ISSUE THREAD

**Issue by urworstknight518** [interlark/ustvgo-tvguide#1]
I can't get the xml link to load in kodi. i add the raw link and all i get is channel id's no shows, the m3u8 loads great..*small request add the auto updating xml to the server with the m3u8*

please any help will be greatly appreciated

**Comment by interlark** [comment]
Fixed with ff79a34789a375f3d3df3a322694a2b90584b29c. Now Kodi works with the EPG.

**Comment by interlark** [comment]
I just noticed your request 

> add the auto updating xml to the server with the m3u8

[ustvgo-iptv](https://github.com/interlark/ustvgo-iptv) already has link to the XML in its header. XML updates twice an hour, you can set time interval in Kodi's settings.

I think the problem here is that Kodi [uses](https://github.com/kodi-pvr/pvr.iptvsimple/commit/66970f6af46cb33a209194bbb714c8f28ced57af) `x-tvg-url` attribute instead of common `url-tvg` and that's why it can't auto-load tvguide. I think I could add `x-tvg-url` attriubute to [ustvgo-iptv](https://github.com/interlark/ustvgo-iptv) along `url-tvg`.

**Comment by urworstknight518** [comment]
thank you, i'll go test

edit: Works Perfect! thank you very much, this is amazing

**Comment by interlark** [comment]
After some investigations I see that Kodi already [support](https://github.com/kodi-pvr/pvr.iptvsimple/commit/de90b31cc2b84d2aedb72d87befe72cb1afede52) `url-tvg`, so all you need is to update your [addon](https://github.com/kodi-pvr/pvr.iptvsimple) to the latest version and your EPG URL from `ustvgo.m3u8` would be grabbed automatically if none was set in settings manually.

**Comment by urworstknight518** [comment]
i don't have a m3u8 file only the .exe file, sorry i'm very new at this, the addon i'm using is simple client, they must not have updated. i see i may have confused you about my request, i was talking about adding the xml to it to connect like the playlist file.. ip:port/xml (english is not my best)

**Comment by interlark** [comment]
Oh, I think I got you. Proxying EPG XML along m3u8 playlist would be easier to handle by end users, in this case all the links would be in one place:
- http://127.0.0.1:6363/ustvgo.m3u8
- http://127.0.0.1:6363/tvguide.xml

Sure, I will add it, nice idea.

**Comment by interlark** [comment]
EPG could be accessed with http://127.0.0.1:6363/tvguide.xml since [v0.1.5](https://github.com/interlark/ustvgo-iptv/releases/tag/v0.1.5) release.
